build:
  image: node:4.2
  commands:
    - npm install

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-nuget
    tag: latest
    when:
      branch: master

plugin:
  name: Nuget
  desc: Publish Artifacts to a NuGet repository
  type: publish
  image: plugins/drone-nuget
  labels:
    - publish
    - nuget
