pipeline:
  test:
    image: node:4.2
    commands:
    - make install
    - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-nuget
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: NuGet
  desc: Publish files and artifacts to NuGet repository
  type: publish
  image: plugins/drone-nuget
  labels:
    - nuget
